name: companies_assets
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  google_fonts:
  flutter_screenutil:
  auto_route:
  json_annotation: ^4.9.0
  get_it:
  injectable:
  copy_with_extension:
  dartz:
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter
  auto_route_generator:
  injectable_generator:
  json_serializable: ^6.8.0
  copy_with_extension_gen:
  build_runner:

flutter: 
  uses-material-design: true
  assets:
    - assets/

