name: companies_assets
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  google_fonts:
  flutter_screenutil:
  data_table_2:
  auto_route:

  isar:
  isar_flutter_libs:
  path_provider:
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter
  auto_route_generator:
  isar_generator:
  build_runner:

flutter: 
  uses-material-design: true
  assets:
    - assets/

